import { Injectable, Logger } from '@nestjs/common';
import { ChatPromptTemplate } from '@langchain/core/prompts';
import { z } from 'zod';
import { AiChatService } from '../ai/ai-chat.service';
import { ChatMessagePayload, StructuredObjectSchema } from '../ai/types/chat.types';
import { CopilotAgentContext, CopilotAgentGeneration } from './types/copilot-agent.types';

const replySchema = z.object({
    action: z.enum(['reply', 'clarify', 'escalate']),
    confidence: z.number().min(0).max(1),
    draftReply: z.string().min(1).max(1200),
    clarifyQuestion: z.string().min(1).max(200).optional(),
    ticketSuggestion: z
        .object({
            title: z.string().min(1).max(120),
            description: z.string().min(1).max(500),
            priority: z.enum(['low', 'medium', 'high']),
        })
        .optional(),
    extractedCustomerFacts: z.array(z.string().min(1).max(120)).max(3).default([]),
});

@Injectable()
export class CopilotAgentService {
    private readonly logger = new Logger(CopilotAgentService.name);

    constructor(private readonly aiChatService: AiChatService) {}

    isEnabled(): boolean {
        return this.aiChatService.isEnabled();
    }

    async generateDecision(context: CopilotAgentContext): Promise<CopilotAgentGeneration> {
        const prompt = await this.buildPrompt(context);
        const response = await this.aiChatService.generate({
            messages: prompt,
            responseSchema: this.buildResponseSchema(),
        });

        this.logger.log(`AI draft generated by provider=${response.provider} model=${response.model}`);

        const parsed = replySchema.parse(this.extractJsonPayload(response.text));
        return {
            provider: response.provider,
            model: response.model,
            decision: parsed,
        };
    }

    private async buildPrompt(context: CopilotAgentContext): Promise<ChatMessagePayload[]> {
        const promptTemplate = ChatPromptTemplate.fromMessages([
            [
                'system',
                [
                    '你是一个电商客服 Copilot 决策助手。',
                    '你的任务不是闲聊，而是基于知识库、客户历史信息、会话摘要，输出一个严谨的 JSON 决策结果。',
                    '必须遵守这些规则：',
                    '1. 只能基于输入里的事实作答，不能编造政策、订单状态或额外承诺。',
                    '2. 如果知识引用为空，优先选择 clarify 或 escalate，不要直接给确定性结论。',
                    '3. clarifyQuestion 只在 action=clarify 时填写。',
                    '4. ticketSuggestion 只在 action=escalate 时填写。',
                    '5. extractedCustomerFacts 只能提取用户问题中明确出现、且适合作为长期记忆保存的稳定事实，最多 3 条。',
                    '6. draftReply 要能让人工客服直接复制给客户，语气专业、简洁、自然。',
                    '7. 你必须只输出 JSON 对象，不要输出 Markdown，不要解释。',
                ].join('\n'),
            ],
            ['user', ['请根据下面输入生成客服草稿决策：', JSON.stringify(context, null, 2)].join('\n')],
        ]);

        const messages = await promptTemplate.formatMessages({});

        return messages.map((message) => ({
            role: this.mapRole(message.getType()),
            content: typeof message.content === 'string' ? message.content : JSON.stringify(message.content),
            name: message.name,
        }));
    }

    private buildResponseSchema(): StructuredObjectSchema {
        return {
            type: 'object',
            required: ['action', 'confidence', 'draftReply', 'extractedCustomerFacts'],
            properties: {
                action: {
                    type: 'string',
                    enum: ['reply', 'clarify', 'escalate'],
                },
                confidence: {
                    type: 'number',
                    minimum: 0,
                    maximum: 1,
                },
                draftReply: {
                    type: 'string',
                },
                clarifyQuestion: {
                    type: 'string',
                },
                ticketSuggestion: {
                    type: 'object',
                    properties: {
                        title: { type: 'string' },
                        description: { type: 'string' },
                        priority: {
                            type: 'string',
                            enum: ['low', 'medium', 'high'],
                        },
                    },
                },
                extractedCustomerFacts: {
                    type: 'array',
                    items: {
                        type: 'string',
                    },
                },
            },
        };
    }

    private extractJsonPayload(text: string): unknown {
        const normalized = text.trim();

        if (normalized.startsWith('{') && normalized.endsWith('}')) {
            return JSON.parse(normalized);
        }

        const fencedMatch = normalized.match(/```json\s*([\s\S]*?)\s*```/i);
        if (fencedMatch?.[1]) {
            return JSON.parse(fencedMatch[1]);
        }

        const firstBrace = normalized.indexOf('{');
        const lastBrace = normalized.lastIndexOf('}');
        if (firstBrace >= 0 && lastBrace > firstBrace) {
            return JSON.parse(normalized.slice(firstBrace, lastBrace + 1));
        }

        throw new Error('AI 返回内容不是合法 JSON');
    }

    private mapRole(role: string): ChatMessagePayload['role'] {
        if (role === 'system') {
            return 'system';
        }
        if (role === 'ai') {
            return 'assistant';
        }
        return 'user';
    }
}
